### ISSUE TITLE
弹出多个升级提示窗口

### ISSUE THREAD

**Issue by lajicab** [iccfish/FSLib.App.SimpleUpdater#11]
用最简单的整合方式做的
var updater = App.SimpleUpdater.Updater.CheckUpdateSimple(UpdateUrl, "update_c.xml");
但是会弹出3个提示升级的窗口出来

**Comment by iccfish** [comment]
使用的是nuget包还是自行编译的源码？如果是自行编译的源码，可在事件触发的时候打断点看看挂载了几次。
如果可能的话，能提供个会出问题的例子更好。

**Comment by lajicab** [comment]
看来是我应用程序的问题，重建一个没有问题。。。

**Comment by lajicab** [comment]
我原始的项目有些复杂，接手的文档不全，最后还是用了一个笨办法改造你的升级组件解决的， 代码：

> 

		[DllImport("user32.dll")]
		private static extern IntPtr FindWindow(string lpClassName, string lpWindowName); 
		#endregion

> 
                /// <summary>
		///   构造函数
		/// </summary>
		public UpdateFound()
		{
            //这里保证不弹出多个升级提示窗口,如果发现相同窗口，干掉自己。
			if (FindWindow(null, "发现新版本") != IntPtr.Zero)
			{
				Console.WriteLine("找到句柄---直接不进行初始化");
				this.Close();
				this.Dispose();
				return;
			}

			InitializeComponent();

			this.lnkSoft.Click += (s, e) => System.Diagnostics.Process.Start(Updater.Instance.Context.UpdateInfo.PublishUrl);
			FormClosing += UpdateFound_FormClosing;
		}

**Comment by iccfish** [comment]
额……这解决方法好奇怪……

**Comment by lajicab** [comment]
我也是没有办法，项目比较大，由于权限原因，有重启之类的，可能会造成启动多个simpleupdate实例，只好控制整个系统只能弹出一个这个窗口标题的窗口好了，懒得折腾了，看代码看得发昏。

**Comment by iccfish** [comment]
我倒没事，就是挺同情你的 :joy:

**Comment by lajicab** [comment]
哥们，你的这个组件很好，开源出来，解决我自己写升级组件的问题，非常感谢！
