### ISSUE TITLE
更新线程卡住了

### ISSUE THREAD

**Issue by chpiter** [iccfish/FSLib.App.SimpleUpdater#27]
xxx.exe Information: 0 : 正在从 http://xxx/xxx/xxx/update_c.xml?0.327457970160739 下载升级信息
    DateTime=2019-07-30T15:58:20.0003233Z
求助，谢谢

**Comment by iccfish** [comment]
这个地址是否确定可以访问？

**Comment by chpiter** [comment]
> 这个地址是否确定可以访问？

我项目中配置的地址是可以访问的，但是因为跨机房，跨区域，所以访问可能会出现不稳定的情况，可能是网络方面，log中没有抛出错误信息

**Comment by iccfish** [comment]
如果可以的话，可以试试用Fiddler抓包，看看网络请求的状态。

**Comment by chpiter** [comment]
> 如果可以的话，可以试试用Fiddler抓包，看看网络请求的状态。

好的，我试试。信息

**Comment by hodrag** [comment]
应该是你的更新地址写错了，checkupdatesimple有2个参数
