### ISSUE TITLE
部分界面文字有误，部分文字可优化

### ISSUE THREAD

**Issue by Assur** [iccfish/FSLib.App.SimpleUpdater#32]
1.下面截图的提示可以再优化，比如，生成之前清理目标目录，弹出提示文字在此项选中的时候应该提示清空目录之类的文字
![20200421165137](https://user-images.githubusercontent.com/5087740/79846055-87165980-83f0-11ea-8de4-e0027da61ded.jpg)

2.最近版本等文字描述变量反了
![20200421165147](https://user-images.githubusercontent.com/5087740/79846448-0b68dc80-83f1-11ea-89f0-d4e8a07eaa62.png)

3.更新后执行  tip文字描述有误，应该是“更新后执行”而不是“更新前执行”
![20200421165156](https://user-images.githubusercontent.com/5087740/79846565-2f2c2280-83f1-11ea-93f0-b0d94935f942.jpg)

**Comment by iccfish** [comment]
第二条似乎没有复现。
