### ISSUE TITLE
使用自签名SSL证书时，升级包下载失败

### ISSUE THREAD

**Issue by andywu188** [iccfish/FSLib.App.SimpleUpdater#41]
当服务端使用了自签名SSL证书时，升级包zip包无法下载，因为自签名证书不受信任，建议忽略证书错误，或者增加个配置项。

相关代码示例如下：

/// <summary>
/// Together with the AcceptAllCertifications method right
/// below this causes to bypass errors caused by SLL-Errors.
/// </summary>
public static void IgnoreBadCertificates()
{
    System.Net.ServicePointManager.ServerCertificateValidationCallback += (sender, cert, chain, sslPolicyErrors) => true;
} 

在网络请求之前调用一次即可，全局生效。
例如可以在Updater 类 void UpdateInternal(object sender, RunworkEventArgs e)中第一行补上调用代码。

相关错误日志如下：
  DateTime=2022-06-08T07:13:09.9898762Z
AutoUpdater.exe Information: 0 : 正在初始化 3 个WebClient
    DateTime=2022-06-08T07:13:09.9918763Z
AutoUpdater.exe Information: 0 : 包【8DE45295C3779350F5D016F69CE54A79.zip】开始下载
    DateTime=2022-06-08T07:13:10.0088773Z
AutoUpdater.exe Information: 0 : 包【0D8F45BE38A74ED2B2CF2F3147E0F7C2.zip】开始下载
    DateTime=2022-06-08T07:13:10.2888933Z
AutoUpdater.exe Information: 0 : 包【07B2107DBA38E1B7550CBD400FA2C66D.zip】开始下载
    DateTime=2022-06-08T07:13:10.2978938Z
AutoUpdater.exe Warning: 0 : 包【0D8F45BE38A74ED2B2CF2F3147E0F7C2.zip】下载失败：基础连接已经关闭: 未能为 SSL/TLS 安全通道建立信任关系。
    DateTime=2022-06-08T07:13:10.5729096Z
AutoUpdater.exe Warning: 0 : 包【8DE45295C3779350F5D016F69CE54A79.zip】下载失败：基础连接已经关闭: 未能为 SSL/TLS 安全通道建立信任关系。
    DateTime=2022-06-08T07:13:10.5729096Z
AutoUpdater.exe Warning: 0 : 包【07B2107DBA38E1B7550CBD400FA2C66D.zip】下载失败：基础连接已经关闭: 未能为 SSL/TLS 安全通道建立信任关系。

**Comment by lianglj** [comment]
您好，邮件已收到

**Comment by andywu188** [comment]
以下版本已修复，如需要，请自行合并:
https://github.com/iccfish/FSLib.App.SimpleUpdater/commit/0863f5c3d305269547602eae9713b6133d33ffe1
